<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPCI9Dur\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPCI9Dur/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPCI9Dur.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPCI9Dur\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPCI9Dur\App_KernelDevDebugContainer([
    'container.build_hash' => 'PCI9Dur',
    'container.build_id' => 'fb06c0c9',
    'container.build_time' => 1696446826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPCI9Dur');
